### ISSUE TITLE
기능적 요구사항 정리

### ISSUE THREAD

**Issue by ShimJaewook** [BugsLIfee/final#1]
#트렐로 링크 : https://trello.com/b/CxH8yfJh/moa-moa

지난 시간 에러를 잡아주는 개발자 웹 커뮤니티에 대해 주제를 나누어 보았습니다.

지금까지 나온 기능들은 아래와 같습니다.

1. (랭킹)질문자 랭킹
2. (랭킹)답변자 랭킹
3. (내정보)내질문 모아보기
4. (내정보)내답변 모아보기
5. (유저)로그인
6. (유저)회원가입
7. (게시판)질문 게시판
8. (게시판)질문 검색

추가 의견 있으시면 댓글 달아 주세요~~

**Comment by dalsomin** [comment]
(포인트) 포인트기능을 추가하고 + 출석도장 추가했으면 좋겠습니다 😄

**Comment by Kayaleeeee** [comment]
(채팅) 질문자와 1:1 채팅
질문자와 1:1 채팅 구현 어떨까요? 
하지만 우선순위는 최하위로 생각하고 구현할 시간 남으면 추가하면 좋을것 같아요   🤸‍♀️

**Comment by ShimJaewook** [comment]
+(결제)결제 시스템
+(게시판)질문 세부 검색(언어, 작성자, 제목...)
+(개인정보)개인 통계(해결한 문제 수, 올린 질문 리스트, 사용 언어...)

**Comment by 0505sdj** [comment]
답변 공개/비공개 기능 (질문자 권한)
웹 컴파일러 기능
팝업형 주석처리 혹은 각주처리
