### ISSUE TITLE
2020-10-10 비대면 서로 진행상황 공유

### ISSUE THREAD

**Issue by dalsomin** [BugsLIfee/final#29]
-  ⭐ 오늘목표 : 오늘까지 한가지 기능 프론트+백엔드 CRUD 완성하기

- [ ] 재욱 : question CRUD
- [ ] 가연: user UD
- [ ] 소민 : info CRUD
- [ ] 동주: ?

-  현재까지 진행상황 done, -ing, todo 적어서 댓글달기
-  내일 1시까지 사당역 크레이저커피숍

✔️ 모듈프로젝트는 최대한 간단하게 할거니까 부담은 갖지말되 
각자 맡은거 **완성도있게 1-2가지 기능만 구현**합시다.

-> 지라 및 아이템회의는 모듈프로젝트 완성후 합시다 ! (월부터)

**Comment by dalsomin** [comment]
- [x] done: info Create, Read, Update 까지 

- [ ] -ing: info data 넣고, info 뷰 말끔하게...

- [ ]  todo : info 전체적으로 말끔하게 정리, 시간남으면 auth시작

* **특이사항**: 오늘 취업설명회, 리눅스마스터 시험이 있어요....🤦 

* **장애사항**: info ui 가 엉망이라 걱정입니다... 😭

**Comment by ShimJaewook** [comment]
done: question 댓글, 백엔드 구조잡기

 -ing: question crud 연동

 todo : answer 댓글 뷰 수정, 나머지 CRUD

특이사항: 없습니당ㅎㅎ

장애사항: 답변창 댓글이 안달려요

**Comment by Kayaleeeee** [comment]
done: 백엔드 user update, list, add 기능 완성
-ing : 프론트 / 백 기능 연결 / model 생성
todo: 프론트에서 user api 처리하기
특이사항 :지금  User객체를 다른 곳에도 공유해야되는데~!~! 어떻게 구조를 밖으로 뺄지 모르겠어요

**Comment by 0505sdj** [comment]
done: question : 백엔드 구조잡기

-ing: list Read 연동, 테이블 구상

todo : 리스트에서 디테일로 라우팅 기능

특이사항:  아직없습니다
