### ISSUE TITLE
2020-10-11 사당역 회의 결과

### ISSUE THREAD

**Issue by Kayaleeeee** [BugsLIfee/final#32]
오늘 한 일
- [x] API 연결
- [x] 백엔드 CRUD 구성 완료
- [x] proxy 에러 및 타입에러 정복 ❣️

내일 할 일 (강남역 1시 반 회의)
- [ ] 아이템 회의
- [ ] 테이블구조 짜기 회의

**Comment by Kayaleeeee** [comment]
done: 회원가입 완성 /  데이터 연결

 -ing: 회원 정보 수정 / updateUser()

 todo : 회원 정보 수정 페이지 완성

**Comment by dalsomin** [comment]
done: data 넣기, qna 연결 
-ing: qna R
todo :qnaCUD
