### ISSUE TITLE
0929 강남역회의 in UCL

### ISSUE THREAD

**Issue by dalsomin** [BugsLIfee/final#4]
오늘 회의 목표입니다 😍 

- [x] 테마색정하기

- [x] 로고정하기

- [x] 사업계획서 80프로완성

**Comment by dalsomin** [comment]
오늘 로고 정했습니다.

**Comment by ShimJaewook** [comment]
1. 테마색 : #6ef780, #6a38ff
2. 로고 : 무당벌레를 시그니쳐로. 
  - 초록 무당벌레 : 답변채택완료(해결)
  - 노랑 무당벌레 : 답변미채택
  - 빨강 무당벌레 : 답변이 없는 질문

**Comment by Kayaleeeee** [comment]
1. 테마색 연두 / 혹은 알록달록
2. 레퍼런스 페이지
- [연두]
https://dribbble.com/shots/3863412-naea-landing-page/attachments/876316
https://www.behance.net/gallery/65800529/Techoners-Website-UI-Design

- [알록달록]
https://office.hancom.com/

**Comment by 0505sdj** [comment]
테마색 : 초록(Success) 노랑(Warning) 빨강(Error) / 전체적으로는 흰색으로 깔끔하고 모던하고 세련되게~
로고 : 무당벌레에 </> 까지 추가~
